### ISSUE TITLE
Error: can't convert nil into String

### ISSUE THREAD

**Issue by tkrotoff** [mackuba/jslint_on_rails#13]
Hi,

I'm using Rails 3.2.3 and jslint_on_rails 1.1 under Windows 7 x64 and this is the error that I get:

```
$ bundle
Fetching gem metadata from https://rubygems.org/.......
[...]
Installing jslint_on_rails (1.1)
[...]
Using rails (3.2.3)
[...]
Your bundle is complete!

$ rake jslint:copy_config
rake aborted!
can't convert nil into String

$ rake jslint --trace
rake aborted!
can't convert nil into String
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint/utils.rb:14:in `join'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint/utils.rb:14:in `<module:JSLint>'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint/utils.rb:4:in `<top (required)>'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint.rb:2:in `require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint.rb:2:in `<top (required)>'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint_on_rails.rb:1:in `require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/jslint_on_rails-1.1/lib/jslint_on_rails.rb:1:in `<top (required)>'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:68:in `require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:66:in `each'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:66:in `block in require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:55:in `each'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/runtime.rb:55:in `require'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler.rb:118:in `require'
c:/Users/Tanguy/MyApp/config/application.rb:7:in `<top (required)>'
c:/Ruby193/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
c:/Ruby193/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
c:/Users/Tanguy/MyApp/Rakefile:5:in `<top (required)>'
c:/Ruby193/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load'
c:/Ruby193/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load_rakefile'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:501:in `raw_load_rakefile'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:82:in `block in load_rakefile'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:81:in `load_rakefile'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:65:in `block in run'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:63:in `run'
c:/Ruby193/bin/rake:32:in `<main>'
```

Regards,

**Comment by deltadd** [comment]
Same issue.

**Comment by mrhaddad** [comment]
+1

**Comment by mackuba** [comment]
You're right, it looks like the code I've added recently behaves differently when including jslint from local path (which is how I test it) than when loading it as a normal gem, that's why I haven't noticed that. I'll try to push a fix soon.

**Comment by mackuba** [comment]
Try version 1.1.1, it should be ok now.
